name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          python -m pip install --user poetry==1.1.9
          poetry config virtualenvs.in-project true
          poetry --version
          poetry install
          yarn install --frozen-lockfile --non-interactive
      - name: Run linters
        run: |
          ./s/lint
      - name: Validate stubs
        env:
          DJANGO_SETTINGS_MODULE: bear.settings
        run: |
          export PYTHONPATH="$(pwd)/tests/bear"
          poetry run stubtest django
